### ISSUE TITLE
initial observations on python script

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#115]
### Description

- Remove need to specify order. Assume that configs are already in order in stack def if order is not specified.
- Got stuck on parallel deploy. Key protect and watsonx saas ready to validate, but script never picked them up as ready
- Default to parallel deploy (when issues there are fixed)
- Remove default input values from sample_deploy_config as they override the manually inputted valie
- Add sample deploy config json to .gitignore
- If config is already validating when script is run : script stop and exit

```
ERROR:root:error executing command: ibmcloud project config-validate --project-id 3349ca8f-2f71-4d9b-9a42-ccbaf238864d --id c7b8313f-5bf0-4068-a415-0e8d9fb590aa
ERROR:root:Output: ...
Error response body

Error: FAILED
The config name "RAG-1 - Account Infrastructure Base" currently cannot run requested operation. It is in state "validating"
```

**Comment by ocofaigh** [comment]
Projects now support deploy all - no longer need python script
