### ISSUE TITLE
Add option to select jp-tok region 

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#118]
### Description

- Ensure that all services in the stack can deploy in that region.
- If this works - add support for Japan jp-tok region at the stack level https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/df61899f03da8e2f98ed26948eb93a92a8a375b7/ibm_catalog.json#L219

**Comment by Soaib024** [comment]
@vburckhardt Watsonx SaaS DA only supports us-south and eu-de

https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/d243f4db0960e337c45e6c940659bdcdf2256748/variables.tf#L14

**Comment by vburckhardt** [comment]
@Soaib024 - I think watson services can be deployed in jp however, and if so, the approach here would be to update the watsonx saas da.

**Comment by Soaib024** [comment]
Occupied with some other works, so unassigning for now

**Comment by ocofaigh** [comment]
From @shemau :

- Today, the only service that does not support jp-tok is watson.governance. It only supports eu-de and us-south.

So I think we cannot add jp-tok support to the stack

**Comment by akocbek** [comment]
indeed, only eu-de and us-south supported https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/main/main.tf#L180

**Comment by ocofaigh** [comment]
No support in watson.governance so we cannot support in the stack - closing
