### ISSUE TITLE
Deploying the stack with existing resource group

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#127]
### Description

In a scenario where there is a "central" deployment of the stack components (security / watson SaaS shared instances) and a number of dependent stack deployments with only watson sub-resources and separate ALM / application config instances I need to be able to refer to an existing resource group instead of provisioning a new one in the Account Infrastructure Base.
Essentially, the Account Infrastructure Base DA becomes just a reference point where I can provide an existing resource group so that other members of the stack can keep pointing to the output of the Account  Infrastructure Base DA.

The resource groups for the subsequent / additional stack deployments may be managed by the central team along with the IAM permissions scoped to those resource groups. Therefore it may not be feasible for the additional stack deployments to be allowed to create their own resource group and/or modify the account settings.

This will  probably require the Account  Infrastructure Base DA to have options to suppress creation of resource groups and changes of account settings as well as the stack to have a parameter to indicate the usage of an existing resource group.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Related? https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/pull/160

**Comment by in-1911** [comment]
The release 1.11.0 of the Account Infrastructure DA now can use existing RG, but the stack needs to wire that to a new input to be able to switch between provisioning a new RG and using a specified existing DA.

I think if a new input (e.g. `existing_resource_group_name`) with `__NULL__` default is added and wired to `existing_*_resource_group_name` in the Account Infrastructure DA, then I should be able to switch the RG provisioning from the stack's top level.

We need to make sure that the RG inputs in the member DAs are wired to the **output** of the Account Infrastructure DA, not the input at the of the stack.

**Comment by in-1911** [comment]
The Account Infrastructure DA 1.11.0 is out and if we add the new parameter to the stack as described in the previous comment, it would fulfill this requirement

**Comment by MatthewLemmond** [comment]
The stack now supports passing an existing resource group so closing this issue
