### ISSUE TITLE
Prefix is not passed to KMS DA

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#129]
Prefix value from the stack input needs to be passed to the KMS DA

https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/f12b0268ecb7c4ad05dbdbe49e65e21dd86cded5/stack_definition.json#L124

**Comment by ocofaigh** [comment]
This is fixed in the Core Security services stack which is consumed by the genai stack. RAG stack is being updated to consume genai stack (tracked here https://github.ibm.com/goldeneye/issues/issues/9896) - closing this issue
