### ISSUE TITLE
Enable skipping SCC provisioning

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#131]
### Description

In a scenario where the stack is deployed while re-using most of the resources (security services, Watson SaaS), I would like to be able to configure the stack variables to skip provisioning a new SCC instance. At some point I might still want to be able to create some attachments, but currently the SCC DA does not have much fine-grained control over that. 

At the moment, I would have to just not deploy the SCC DA if I do not want to create a new SCC instance. Another option is to just delete that member DA from the stack instance in the project. Neither option would work if we will be creating SCC attachments through the stack while re-using the instance.

This feature would probably require a change in the SCC DA as well (to enable using an existing instance) or a change in stack framework that allows to override the stack member with pre-defined output values - to keep any wiring within the stack intact.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@in-1911 In https://github.com/terraform-ibm-modules/terraform-ibm-scc-da/issues/140 we are adding the ability to pass an existing SCC instance to the SCC DA. That will atr least cover the use case of being able to create attachements in an existing instance.
