### ISSUE TITLE
Selective provisioning of observability resources

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#132]
### Description

In a scenario where the stack is deployed while re-using most of the resources (security services, Watson SaaS), I would like to be able to configure the stack variables to skip provisioning of some (or all) of the new observability resources by the corresponding member DA.
Because of the complexity of the resource configuration something like an override.json approach may be a better option here.

- ATracker routes and targets
- LogDNA instance
- Cloud Monitoring instances
- COS buckets for the above

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
This should be exposed in the Core security services stack first, which the RAG stack would then consume

**Comment by Khuzaima05** [comment]
@ocofaigh 

Should I expose the four boolean variables— Activity Tracker routes and targets, LogDNA instance, Cloud Monitoring instances, and COS buckets—in the input and output of the core security services stack definition, and then utilize them within the stack-retrieval-augmented-generation module's stack definition?

**Comment by Khuzaima05** [comment]
As per discussion, no implementation is needed at this time. I am unassigning myself from this task as I am currently focusing on other high-priority tasks.

**Comment by Khuzaima05** [comment]
PR merged, Closing this issue
