### ISSUE TITLE
Failure when skipping WML project creation by Watson SaaS DA

### ISSUE THREAD

**Issue by in-1911** [terraform-ibm-modules/stack-retrieval-augmented-generation#133]
### Description

In a scenario where the stack is deployed while re-using most of the resources (security services, Watson SaaS), I would like to be able to configure the stack variables to skip creating a new project (<prefix>-demo by default).

The Watson SaaS rel.1.1.2 allows passing `__NULL__` as project name and will skip the project creation.

With the current stack available in the catalog (rel.1.0.0) changing the watsonx_project_name  from `demo` to `__NULL__` results in terraform error when it tries to destroy the project resource (due to https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/03ac1a86afd1cdaad37aacb042a070505fc3b4ab/configure_project/main.tf#L59 )

Upgrading Watson SaaS DA to release 1.1.4+ in the stack definitioin should resolve the error.

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by in-1911** [comment]
Seems like Watson SaaS needs some fixes as well - https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/issues/97

**Comment by in-1911** [comment]
Upgrade to Watson SaaS 1.1.4+ should fix that.

**Comment by ocofaigh** [comment]
@andreainnocenti should this be assigned to someone on your team?
