### ISSUE TITLE
With existing HPCS CRN unable to see any associated resources in the HPCS instance.

### ISSUE THREAD

**Issue by Ak-sky** [terraform-ibm-modules/stack-retrieval-augmented-generation#139]
When using HPCS CRN for `existing_kms_instance_crn`, deployement is successful but unable to see any associated resources in the HPCS instance.

**Comment by ocofaigh** [comment]
@Ak-sky what do you mean by "any associated resources in the HPCS instance"? Are you talking about the key ring and keys?

**Comment by Ak-sky** [comment]
> @Ak-sky what do you mean by "any associated resources in the HPCS instance"? Are you talking about the key ring and keys?

Yes, like in KP we see the info
<img width="1135" alt="image" src="https://media.github.ibm.com/user/410235/files/98cc8c07-e633-46f7-a839-dbcfadb8631a">

**Comment by iamar7** [comment]
Was able to see the `keys` and `key_rings` in the instance. 

<img width="1692" alt="Screenshot 2024-07-08 at 6 03 02 AM" src="https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/ac905eeb-264f-4ed2-bbb0-ec3d3c4ef9f7">

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/11ba00e6-0f7f-4142-97e1-8dd5b9372d80)

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/1aec34db-ac89-41da-9a86-641f72256b51)
