### ISSUE TITLE
Narrow down test scenarios for stack

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#17]
Include in doc

**Comment by vburckhardt** [comment]
Test scenarios for mid-may timeframe:
- "Happy path" - run stack with all existing defaults. Ensure deployment end to end.
- **Multiple deployment**: Multiple deployment of the stack in same account (using different input prefix)
- **Existing resources**
   - Existing secret manager instance
   - Existing key protect instance (passing existing instance id as input)
   - Use of existing HPCS instance (post mid-may timeframe)
- Run with minimal API key permissions (as documented) for deployer + watsonxadmn
- SCC scanning (AI guardrail profile - except documented exceptions)
- Test with same and different watson ai API key and ibmcloud api key

Post mid-may timeframe:
- Use of trusted profile (for the 'deployer' identity - not for watsonx ai)

**Comment by abiazett** [comment]
@vburckhardt on the Happy Path, can we have 2 subscenarios:
- One using the current script which deploys all DAs in sequence (and hopefully will be replaced by the deploy all button)
- Another one for using the UI to provide the inputs (instead of the json input file) and deploy one by one of the component DAs.

**Comment by in-1911** [comment]
I would add the following cases, but some of them may require some redesign of the DAs in the stack.
Currently the stack is tailored for deploying essentially a single application in a new cloud account.
If a customer wants to maintain and evolve their environment where the Watson components are deployed, some incremental capability would be needed.

- After the stack is deployed initially, incrementally add more Watson services (e.g. governance)
- After the stack is deployed initially, incrementally add more Watson service instances, in addition to existing ones.
- Incrementally add new projects or applications (new configuration? additional entries in ALM DA?)
- Incrementally remove projects or applications

**Comment by vburckhardt** [comment]
@abiazett - I'll add the UI specifically. The current script is only meant to be used by the engineer team until Project provides a Deploy All button. It is not planned to be documented for use by customers.

**Comment by vburckhardt** [comment]
Complete with tickets created for each scenario.
