### ISSUE TITLE
ROKS variation: document  User API key creator role needs in panel

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#204]
IAM Identity service. In addition to the Administrator role, when deploying the Standard variation of the Deployable Architecture, explicitly assign the User API key creator role, as it is mandatory for a successful OpenShift cluster deployment.

This is documented in README.md but missing from this screen

![image](https://github.com/user-attachments/assets/155894ad-96f2-4a4b-8989-26950e14af12)

**Comment by toddgiguere** [comment]
PR for development RAG stack fork created: https://github.com/terraform-ibm-modules/dev-rag/pull/73

**Comment by toddgiguere** [comment]
Documentation has been released: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/releases/tag/v2.0.1
