### ISSUE TITLE
test: "Happy path" - run stack with all existing defaults. Ensure deployment end to end, including app up and running.

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#31]
### Description

- Through UI
- Through deploy script https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/blob/main/deploy-many.sh

Context: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/17

**Comment by iamar7** [comment]
The deployment of RAG stack through UI and script end to end, including app up and running has been verified.

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/705a03ef-f927-4af8-8d75-4352339b1a70)

Also, verified the CI pipeline status as well.

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/23326e77-fe62-4e58-926d-56c0efa3d511)

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/20831630/f8b0d6f8-5a8c-495d-897c-5c53e23c118e)
