### ISSUE TITLE
test: Destroy path

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#35]
### Description

Undeploy the stack - verify that ALL resources are deleted (check in resource controller)

Context: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/17

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamar7** [comment]
There any two approaches to undeploy the stack and delete all the resources:-

- Delete the project and it will undeploy all the resources associated with the project before deleting.
- Undeploy the stack one by one through the UI.
