### ISSUE TITLE
test: Compliance

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#37]
### Description

    SCC scanning should be green (AI guardrail profile - except documented exceptions)
    Verify compliance posture for each of the underlaying DA

Context: https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/17

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by rajatagarwal-ibm** [comment]
Closing this. Details on the internal issue -  https://github.ibm.com/GoldenEye/issues/issues/8760
