### ISSUE TITLE
test: incremental addition

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#40]
### Description

See https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/issues/17#issuecomment-2073359270

**Comment by akocbek** [comment]
I was able to successfully increase/add components incrementally :
- increase `watson_machine_learning_plan` from `lite` to `essentials`
- increase `watson_studio_plan` from `lite` to `professional` 
- add `watson_discovery_plan` from `no install` to `plus`
- add `watsonx_assistant_plan`  from `no install` to `plus`
- add `watsonx_governance_plan`  from `no install` to `essentials`
