### ISSUE TITLE
"invalid bearer token" error while deploying SaaS DA repo. 

### ISSUE THREAD

**Issue by rajatagarwal-ibm** [terraform-ibm-modules/stack-retrieval-augmented-generation#49]
Hitting the `invalid bearer token` error for SaaS DA deployment in the stack.

Error log: 
```
2024/05/02 11:11:41 Terraform apply | Error: unexpected response code '401': Invalid bearer token: Access token is invalid.
2024/05/02 11:11:41 Terraform apply | 
2024/05/02 11:11:41 Terraform apply |   with module.configure_project.restapi_object.configure_project[0],
2024/05/02 11:11:41 Terraform apply |   on configure_project/main.tf line 3, in resource "restapi_object" "configure_project":
2024/05/02 11:11:41 Terraform apply |    3: resource "restapi_object" "configure_project" {
2024/05/02 11:11:41 Terraform apply | 
```

**Steps to reproduce:**
1. Follow the steps mentioned in this readme - https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation
2. If not passing an actual value for `watsonx_admin_api_key`, it failed with the above error. 

Below are the scenarios I have tested:
* `FAILED` when setting `"watsonx_admin_api_key": null,` 
* `FAILED` when omitting `watsonx_admin_api_key` from the .def.json file.
* `FAILED` when setting same value as `ibmcloud_api_key`.

**P.S.**  - I tried to deploy it in the GE Ops account.

**Comment by Ak-sky** [comment]
Looks like Bearer token was missing when passed to the these 2 shell scripts- https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/78c16f84a3fbfd3b4dd8ec26e9e780fdb1e89851/configure_user/scripts/add_user.sh
and 
https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/78c16f84a3fbfd3b4dd8ec26e9e780fdb1e89851/configure_user/scripts/enforce_account_restriction.sh

**Comment by brendankellyibm** [comment]
How long was the DA running for?

**Comment by Ak-sky** [comment]
After some debugging what I noticed is missing word "Bearer" in `Bearer <TOKEN>` while running the cmd `configure_user/scripts/add_user.sh` causing the shell script to fail (`<stdin>:1): Malformed BOM (while parsing '��')`) at this [line](https://github.com/terraform-ibm-modules/terraform-ibm-watsonx-saas-da/blob/c82832f84fadd5620d027d46ecd7a92af7903a27/configure_user/scripts/add_user.sh#L14).

<img width="941" alt="image" src="https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/4889052/73b69e54-bfbc-4cd1-b87c-8cefc13f6dae">

**Comment by vburckhardt** [comment]
Do we have a theory why this happens only for some users?

**Comment by ocofaigh** [comment]
Stale - closing for now - not been reproduced in number of runs.
