### ISSUE TITLE
Project: missing diagram description

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#57]
### Description

By default, each diagram from each DA is displayed in the stack. However, the title / description of each diagram is missing making things difficult to understand for the end-user.

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/16447795/a4f55b29-eb1a-4339-9bfd-11999791b84e)

**Comment by ocofaigh** [comment]
This is being tracked internally with the projects team. Its not related to any of the code in this repo, so closing here
