### ISSUE TITLE
Project: passing an api key at the stack level in UI is not functional

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#62]
```
 2024/05/07 10:09:34 Terraform plan | Error: ibmcloud_api_key or bluemix_api_key or iam_token and iam_refresh_token must be provided. Please see the documentation on how to configure it
 2024/05/07 10:09:34 Terraform plan | 
 2024/05/07 10:09:34 Terraform plan |   with module.account_infrastructure_base.module.account_settings.data.ibm_iam_account_settings.iam_account_settings,
 2024/05/07 10:09:34 Terraform plan |   on .terraform/modules/account_infrastructure_base.account_settings/main.tf line 8, in data "ibm_iam_account_settings" "iam_account_settings":
 2024/05/07 10:09:34 Terraform plan |    8: data "ibm_iam_account_settings" "iam_account_settings" {
 2024/05/07 10:09:34 Terraform plan | 
 2024/05/07 10:09:35 [1m[31mTerraform PLAN error: Terraform PLAN errorexit status 1[39m[0m
```

### Affected modules

*

### Terraform CLI and Terraform provider versions

* Terraform version:
* Provider version:

### Steps to reproduce (including links and screen captures)

1. Run `terraform apply`

### Anything else

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
From Vincent:

> After a few trial and errors, it seems that removing the explicit wiring on the ibmcloud_apikey input in the stack definition seems to fix the issue. https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/67/commits/d58d4f71c585b088d75b9a047ea31a244a19bb9d
