### ISSUE TITLE
test: two configurations in the same project and does it run independently

### ISSUE THREAD

**Issue by maheshwarishikha** [terraform-ibm-modules/stack-retrieval-augmented-generation#74]
One configuration was added in one project, that failed for Security Service - KMS. Could not redploy KMS because of #73 .

So added a new configuration in the same project. But script (deploy-many.sh) failed with the below error:

```
ibmcloud project config-validate --project-id 2ca20f6a-9fc2-4f82-809c-2987964b0783 --id 9a5e2131-00cb-450e-a4d2-edd6c5af548a --output json
FAILED
There was an error when attempting to resolve the reference ref:../2a - Security Service - Key Management/outputs/key_protect_crn: The project reference to the configuration 349fca6c-0bc1-44cc-a0b2-35abf84a9d10 cannot be found

             
Errors       
StatusCode   0
```

Not sure though, but looks like somehow it is failed because of KMS in previous configuration.

**Comment by vburckhardt** [comment]
Yes, the script assumes that there is only one stack in the project. We can document it, unless this is already addressed in the upcoming python version @daniel-butler-irl ?

**Comment by daniel-butler-irl** [comment]
@maheshwarishikha If you want to try the script you can pull it from my branch https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/pull/76
