### ISSUE TITLE
community catalog: duplicate entries displayed

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#75]
### Description

![image](https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/16447795/08c6b112-b31b-4834-ba99-51de133074e1)

**Comment by ocofaigh** [comment]
Duplication only shows for people with editor access to the catalog, so its expected. You can see one of them has a lock icon (private catalog) and one does not
