### ISSUE TITLE
Error message on screen after approval of each stack item via UI

### ISSUE THREAD

**Issue by maheshwarishikha** [terraform-ibm-modules/stack-retrieval-augmented-generation#89]
Deploying stack via UI. 
- choose any i.e. KMS, validated
- Approved
- After approval, get the following message on screen:
<img width="764" alt="image" src="https://github.com/terraform-ibm-modules/stack-retrieval-augmented-generation/assets/10827415/9994fc9f-0951-4cb6-bbab-3b4b254dd9d9">

- In spite of this, am able to deploy. Deployment is successful too.

**Comment by Ak-sky** [comment]
No error seen after validation and approval-

<img width="1598" alt="image" src="https://media.github.ibm.com/user/410235/files/f13529bc-41dc-4d76-bc79-cf7c79b46cd5">

<img width="1609" alt="image" src="https://media.github.ibm.com/user/410235/files/71c0b15b-69ac-4508-b1fd-9003dafbb3c8">
