### ISSUE TITLE
Onboard CI pipeline to this repo

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/stack-retrieval-augmented-generation#9]
### Description

- pre-commit should contains aspects like json validation, detect secrets.
- end to end test should deploy the full stack

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by daniel-butler-irl** [comment]
Now added
